name: Code Quality

on:
    push:
        branches:
            - "**" 
    pull_request:
        branches:
            - "main"

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                go-version: stable

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v8
              with:
                version: v2.1

            - name: Run Linter
              run: golangci-lint run ./...

            - name: Run Tests
              run: go test -v ./...
