name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0, v1.1.0, etc.

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # The version of goreleaser to use.
          version: latest
          # The arguments to pass to GoReleaser.
          args: release --clean
        env:
          # Your GitHub token is required to create a release.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
